name: Generate requirements outpout from asciidoc file

on:
  push:
    branches:
    - feat/pipeline

jobs:
  generate_pdf:
    runs-on: ubuntu-latest
    name: generating an html 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get build container
      id: generatedRequirements
      uses: tonynv/asciidoctor-action@master
      with:
          program: "asciidoctor -o ./reqOutput/index.html Requirements.adoc"
    - name: Deploy generated file to github pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: requirements-preview # default: gh-pages
        publish_dir: ./reqOutput  # default: public
